# Arrays and Strings

## 1.1 Implement an algorithm to determine if a string has all unique characters. What if you can not use additional data structures?

### Solution 1: Compare each character in string with other characters
Remarks: 
- O(n^2) solution but does not require additional data structures
- Need to check if "a" and "A" are considered the same
- Edge cases: empy string, single character string

In [18]:
def all_unique(input_string):
    
    input_string = input_string.lower()
    
    if input_string=="":
        return True
    
    for i in range(len(input_string)):
        for j in range(i+1, len(input_string)):
            if input_string[i]==input_string[j]:
                return False
            
    return True

In [19]:
test_cases = ["", "a", 'aish', "aaish"]

for test_case in test_cases:
    print(all_unique(test_case))

True
True
True
False


### Solution 2: Keep a track of each 'visited' character

Remarks:
- Requires O(n) space
- O(n) time

In [24]:
def all_unique(input_string):
    
    input_string = input_string.lower()
    
    if input_string=="":
        return True
    
    visited = {} 
    
    for i in range(len(input_string)):
        try:
            if visited[input_string[i]]: #if visited contains the character already
                return False
        except:
            visited[input_string[i]]=1
    
    return True    

In [25]:
test_cases = ["", "a", 'aish', "aaish"]

for test_case in test_cases:
    print(all_unique(test_case))

True
True
True
False


## 1.2 Write code to reverse a C-Style String. (C-String means that “abcd” is represented as five characters, including the null character.)

### Solution: Traverse string and add each character to the back of a new string

Remarks:
- We will use _ to represent the Null character
- O(n) space complexity solution that requires us to create a copy of the string

In [28]:
def reverse_c_string(input_string):
    
    if input_string=="":
        return input_string
    
    reversed_string = "_"
    
    for i in range(len(input_string)-1):
        reversed_string = input_string[i]+reversed_string
        
    return reversed_string
        
        

In [30]:
test_cases = ["_", "a_", 'aish_', "aaish_"]

for test_case in test_cases:
    print(reverse_c_string(test_case))

_
a_
hsia_
hsiaa_


## 1.3 Design an algorithm and write code to remove the duplicate characters in a string without using any additional buffer. NOTE: One or two additional variables are fine. An extra copy of the array is not.
FOLLOW UP
Write the test cases for this method.

### Solution: Check every character against every other

Remarks:
- In Python strings are immutable
- We need to consider the case of spaces. Do we count spaces as duplicates? For now we assume our string is without spaces.
- We also need to confirm whether we drop the first character or the next

In [35]:
def remove_duplicates(input_string):
    
    if input_string=="":
        return input_string
    
    if len(input_string)==1:
        return input_string
    
    for i in len(input_string):
        
        traversable_length = input_string[i+1:]
        j=1
        
        while j<traversable_length:
            
            #removal
            if input_string[i]==input_string[j]:
                input_string = input_string[i:j]+input_string[j+1:]
                
                traversable_length=-1
                j+=1
    
    return input_string

In [39]:
test_cases = ["", "aabc", "aabbccddee", "a", "ababababa", "abcd"]

for test_case in test_cases:
    print(remove_duplicates(test_case))
    


abc
abcde
a
ab
abcd


## 1.4 Write a method to decide if two strings are anagrams or not.

### Solution: Sort the strings and compare by character. 

Remarks:
- If length of strings is different then they cannot be anagrams
- O(logn) for sorting and O(n) for comparing (Timsort)

In [44]:
def is_anagram(string_1, string_2):
    
    if len(string_1)!=len(string_2):
        return False
    
    string_1 = sorted(string_1)
    string_2 = sorted(string_2)
    
    for i in range(len(string_1)):
        if string_1[i]!=string_2[i]:
            return False
    
    return True
    

In [46]:
test_cases = [("mane", "name"), ("", ""), ("man", "name"), ("aabcc", "abbcc")]

for test_case in test_cases:
    print(is_anagram(test_case[0], test_case[1]))

True
True
False
False


## 1.5 Write a method to replace all spaces in a string with ‘%20’.

### Solution: Traverse string and replace

Remarks: 
- Python strings are immutable
- O(n) for traversal

In [50]:
def replace_spaces(input_string):
    
    i=0
    traverse_length = len(input_string)

    while i<traverse_length:
        if input_string[i]==" ":
            input_string = input_string[:i]+"%20"+input_string[i+1:]
            
            traverse_length+=1 #since we have added one extra character
            i+=1
            
        else:
            i+=1
    
    return input_string
            

In [51]:
test_cases = ["         ", "aishwarya prabhat", "aish"]

for test_case in test_cases:
    print(replace_spaces(test_case))

%20%20%20%20%20    
aishwarya%20prabhat
aish


## *1.6 Given an image represented by an NxN matrix, where each pixel in the image is 4 bytes, write a method to rotate the image by 90 degrees. Can you do this in place?

### Solution: swap the values around by observing pattern of position change

Remarks:
For a 3x3 matrix
- (0,0)->(0,2)
- (0,1)->(1,2)
- (0,2)->(2,2)


- (1,0)->(0,1)
- (1,1)->(1,1)
- (1,2)->(2,1)


- (2,0)->(0,0)
- (2,1)->(1,0)
- (2,2)->(2,0)

So the pattern seems to be....
- (x_old, y_old)->(x_new=y_old, y_new=(n-1)-x_old)

- To do it in place, we will have to buffer the column whose values are being first replaced. For example when we are filling up column n-1 with values from row 0, the values will be lost if we dont store the values of column n-1 somewhere first.


In [75]:
def rotate_matrix(input_matrix):
    
    n = len(input_matrix)
    matrix_buffer = {}
    
    for i in range(n):
        
        #Add column being replaced to buffer dictionary
        for x in range(n):
            matrix_buffer[(x, n-1-i)] = input_matrix[x][n-1-i]
        
        for j in range(n):
            
            if (i,j) in matrix_buffer.keys(): #position in the matrix has already been filled with new value
                value_to_teleport = matrix_buffer[(i,j)]
                del matrix_buffer[(i,j)] #to save space and not create another copy of the whole matrix
                
            else: #position in the matrix has already been filled with new value
                value_to_teleport = input_matrix[i][j]
                
            new_i = j
            new_j = n-1-i
            
            input_matrix[new_i][new_j] = value_to_teleport

    return input_matrix 
        

In [79]:
test_cases = [numpy.random.randint(low=0, high=5, size=(n,n)) for n in range(5)]
for test_case in test_cases:
    print(test_case)
    print("\n")
    print(rotate_matrix(test_case))
    print("\n")
    print("\n")

[]


[]




[[3]]


[[3]]




[[0 0]
 [1 4]]


[[1 0]
 [4 0]]




[[4 4 2]
 [3 2 1]
 [1 3 2]]


[[1 3 4]
 [3 2 4]
 [2 1 2]]




[[0 0 3 2]
 [3 0 4 1]
 [2 3 0 2]
 [0 3 3 1]]


[[0 2 3 0]
 [3 3 0 0]
 [3 0 4 3]
 [1 2 1 2]]






## *1.7 Write an algorithm such that if an element in an MxN matrix is 0, its entire row and column is set to 0.

### Solution: Traverse matrix looking for 0 and turn entire row and column 0
Remarks:
- To do it in place need to buffer old state otherwise if there is a 0 in the first row, the whole table will turn into 0s because of the new 0s implanted into the matrix
- We also have to make sure we don't replace the buffered position's original value accidentally when trying to buffer rows and columns for a new 0

In [109]:
def implant_zeros(input_matrix):
    
    m = len(input_matrix)
    
    try:
        n = len(input_matrix[0])
    except:
        return input_matrix
    
    
    matrix_buffer = {}
    
    for i in range(m):
        for j in range(n):
            
            if (i,j) in matrix_buffer.keys():
                value_under_consideration = matrix_buffer[(i,j)]
                del matrix_buffer[(i,j)]
            else:
                value_under_consideration = input_matrix[i][j]
                
            if value_under_consideration==0:
                
                #buffer the row
                for j_ in range(j+1,n):
                    if (i,j_) not in matrix_buffer.keys():
                        matrix_buffer[(i,j_)] = input_matrix[i][j_]
                
                #buffer the column
                for i_ in range(i+1, m):
                    if (i_,j) not in matrix_buffer.keys():
                        matrix_buffer[(i_,j)] = input_matrix[i_][j]
                
#                 print(matrix_buffer)
                #turn the whole row into 0s
                for j_ in range(0,n):
                    input_matrix[i][j_] = 0
                
                #turn the whole column into 0s
                for i_ in range(0, m):
                    input_matrix[i_][j] = 0
    
    return input_matrix
           

In [108]:
test_cases = [numpy.random.randint(low=0, high=5, size=(n,n)) for n in range(2,7)]
for test_case in test_cases:
    print(test_case)
    print("\n")
    print(implant_zeros(test_case))
    print("\n")
    print("\n")

[[4 0]
 [0 2]]


[[0 0]
 [0 0]]




[[0 2 3]
 [1 0 3]
 [1 4 4]]


[[0 0 0]
 [0 0 0]
 [0 0 4]]




[[0 4 0 1]
 [3 1 0 0]
 [0 3 0 2]
 [4 3 0 1]]


[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]




[[3 4 4 2 3]
 [1 2 4 1 3]
 [0 1 3 3 1]
 [1 1 2 4 2]
 [1 3 2 2 4]]


[[0 4 4 2 3]
 [0 2 4 1 3]
 [0 0 0 0 0]
 [0 1 2 4 2]
 [0 3 2 2 4]]




[[2 0 4 1 0 3]
 [2 4 2 1 1 4]
 [0 4 1 1 2 2]
 [0 3 4 0 2 2]
 [0 2 2 3 0 3]
 [2 2 1 4 0 4]]


[[0 0 0 0 0 0]
 [0 0 2 0 0 4]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]






## 1.8 Assume you have a method isSubstring which checks if one word is a substring of another. Given two strings, s1 and s2, write code to check if s2 is a rotation of s1 using only one call to isSubstring (i.e., “waterbottle” is a rotation of “erbottlewat”). 

### Solution: Concatenate the two strings and check if s2 is a substring of the concatenated string

In [111]:
def isSubstring(source_string, substring):
    
    return substring in source_string

In [115]:
def check_rotation(s1, s2):
    
    if len(s1)!=len(s2):
        return False
    
    s3 = s1+s1
    return isSubstring(s3, s2)

In [117]:
test_cases = [(" ", " "), ("aishwarya", "yaaishwar"), ("aish", "siah")]

for test_case in test_cases:
    print(check_rotation(test_case[0], test_case[1]))

True
False
False


In [ ]:
siah in aishsiah